sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1024

  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tQpmoDhiqHdCnmByEeR
    access-key-secret: 3S07uQfWxxSzhtRwITMjMyccQKapTl
    bucket-name: sky-itcast-ml1024

  redis:
    host: localhost
    port: 6379
    password: 1024
    database: 0
  wechat:
    appid: wx380fae7131381104
    secret: 4d1d99c7444b446b08b8c6f8dd425807


